### ISSUE TITLE
Camera remain offline when added from android app. 

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-play-android#133]
@liutingdu 

When user adds camera through android app, camera goes  offline.
I have personally tested this issue with many of cameras added through android app. 
What i have found is that the camera online field   "is_online" is blank.

**Comment by marcoherbst** [comment]
Faisal,

Private message the details of the cameras to liuting please

**Comment by liutingdu** [comment]
@faisal2472 Thanks for reporting this :) 

I am able to reproduce this too. After looking into it, the reason is camera will always be offline if it's created by making the API call to ```POST /cameras``` without adding ```is_online=true``` in the API request. 

```is_online``` is an optional field, both Android and iOS client didn't add it to the API call. The camera online/offline status was checked by the server.

This bug is very serious because all cameras created from the Android/iOS apps will stay offline.

It should be caused by a recent change because it was working for me a few days ago..

@marcoherbst @mosic Any idea what has been changed on the server?

**Comment by mosic** [comment]
@liutingdu We made a change recently which uses the response of GET and POST snapshot to change the camera status (if we get a snapshot camera is considered online, otherwise we use the rules from the bottom of this page: https://github.com/evercam/evercam-api/wiki/Media:-Camera-Workers).

Does the Android app send any requests to offline cameras?

**Comment by liutingdu** [comment]
The Android app is not sending requests to cameras if it's not online, I think the iOS app is doing the same.  

Which GET and POST request are you talking about? When should I send the requests?

**Comment by mosic** [comment]
I mean GET live/snapshot and POST recordings/snapshots. The dashboard sends one request to all user's cameras after it's loaded, maybe the apps could do the same? Also when a single camera is opened we send a request.

**Comment by liutingdu** [comment]
It doesn't seem to be a good idea to request live snapshot for all cameras all the time, that would be too many threads and too much data usage.. 

But it seems if the camera is added from API/the app, it will never be online again. I tried open live view in dashboard, and request ```GET live/snapshot```, the camera is still offline ..

**Comment by mosic** [comment]
Hm, okay. This needs discussion with @marcoherbst before changing the behavior of either the app or evercam-media I think.

Either way you could set the `is_online` parameter when creating the camera, there doesn't seem to be a downside with that? If the camera is actually offline the status would be changed on the first snapshot request so no losses there.

**Comment by liutingdu** [comment]
The only downside is right after creating a camera that is actually offline, the app will keep loading live view and show a loading animation, until the user hit return.  I'll do it (set ```is_online=true```) as a temporary fix

**Comment by liutingdu** [comment]
Created the remaining problem as a new issue https://github.com/evercam/evercam-play-android/issues/138
